version: 1.0.0.{build}
os: Visual Studio 2015
services:
- mongodb
environment:
  COVERALLSKEY:
    secure: xKdlZl4wNnzXkiLIb456OFGuLX/BqTJ9XmQUFwIzrjmwAdyDEv/svJXNH3HnvH3q
test: off
build_script:
- cmd: build.cmd ci coverallskey=%COVERALLSKEY%
cache:
- packages -> **\packages.config
