version: 1.0.0.{build}
os: Visual Studio 2015
configuration: Debug
services:
- mongodb
before_build:
- cmd: nuget restore -DisableParallelProcessing -source "https://www.nuget.org/api/v2;https://www.myget.org/F/saladbowlcreative/api/v2"
build:
  project: TicTacToe.sln
  verbosity: minimal
test: on
