// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Akka.Interfaced CodeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using Akka.Interfaced;
using ProtoBuf;
using TypeAlias;
using System.ComponentModel;

#region SurrogateForIRequestTarget

namespace Domain
{
    [ProtoContract]
    public class SurrogateForIRequestTarget
    {
        [ProtoMember(1)] public int Id;

        [ProtoConverter]
        public static SurrogateForIRequestTarget Convert(IRequestTarget value)
        {
            if (value == null) return null;
            return new SurrogateForIRequestTarget { Id = ((BoundActorTarget)value).Id };
        }

        [ProtoConverter]
        public static IRequestTarget Convert(SurrogateForIRequestTarget value)
        {
            if (value == null) return null;
            return new BoundActorTarget(value.Id);
        }
    }
}

#endregion
#region Domain.IGamePlayer

namespace Domain
{
    [PayloadTable(typeof(IGamePlayer), PayloadTableKind.Request)]
    public static class IGamePlayer_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(MakeMove_Invoke), null },
                { typeof(Say_Invoke), null },
            };
        }

        [ProtoContract, TypeAlias]
        public class MakeMove_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadTagOverridable
        {
            [ProtoMember(1)] public Domain.PlacePosition pos;
            [ProtoMember(2)] public System.Int64 playerUserId;

            public Type GetInterfaceType()
            {
                return typeof(IGamePlayer);
            }

            public Task<IValueGetable> InvokeAsync(object __target)
            {
                return null;
            }

            void IPayloadTagOverridable.SetTag(object value)
            {
                playerUserId = (System.Int64)value;
            }
        }

        [ProtoContract, TypeAlias]
        public class Say_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadTagOverridable
        {
            [ProtoMember(1)] public System.String msg;
            [ProtoMember(2)] public System.Int64 playerUserId;

            public Type GetInterfaceType()
            {
                return typeof(IGamePlayer);
            }

            public Task<IValueGetable> InvokeAsync(object __target)
            {
                return null;
            }

            void IPayloadTagOverridable.SetTag(object value)
            {
                playerUserId = (System.Int64)value;
            }
        }
    }

    public interface IGamePlayer_NoReply
    {
        void MakeMove(Domain.PlacePosition pos, System.Int64 playerUserId = 0);
        void Say(System.String msg, System.Int64 playerUserId = 0);
    }

    public class GamePlayerRef : InterfacedActorRef, IGamePlayer, IGamePlayer_NoReply
    {
        public override Type InterfaceType => typeof(IGamePlayer);

        public GamePlayerRef() : base(null)
        {
        }

        public GamePlayerRef(IRequestTarget target) : base(target)
        {
        }

        public GamePlayerRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IGamePlayer_NoReply WithNoReply()
        {
            return this;
        }

        public GamePlayerRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new GamePlayerRef(Target, requestWaiter, Timeout);
        }

        public GamePlayerRef WithTimeout(TimeSpan? timeout)
        {
            return new GamePlayerRef(Target, RequestWaiter, timeout);
        }

        public Task MakeMove(Domain.PlacePosition pos, System.Int64 playerUserId = 0)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePlayer_PayloadTable.MakeMove_Invoke { pos = pos, playerUserId = playerUserId }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task Say(System.String msg, System.Int64 playerUserId = 0)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePlayer_PayloadTable.Say_Invoke { msg = msg, playerUserId = playerUserId }
            };
            return SendRequestAndWait(requestMessage);
        }

        void IGamePlayer_NoReply.MakeMove(Domain.PlacePosition pos, System.Int64 playerUserId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePlayer_PayloadTable.MakeMove_Invoke { pos = pos, playerUserId = playerUserId }
            };
            SendRequest(requestMessage);
        }

        void IGamePlayer_NoReply.Say(System.String msg, System.Int64 playerUserId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePlayer_PayloadTable.Say_Invoke { msg = msg, playerUserId = playerUserId }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIGamePlayer
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIGamePlayer Convert(IGamePlayer value)
        {
            if (value == null) return null;
            return new SurrogateForIGamePlayer { Target = ((GamePlayerRef)value).Target };
        }

        [ProtoConverter]
        public static IGamePlayer Convert(SurrogateForIGamePlayer value)
        {
            if (value == null) return null;
            return new GamePlayerRef(value.Target);
        }
    }
}

#endregion
#region Domain.IUser

namespace Domain
{
    [PayloadTable(typeof(IUser), PayloadTableKind.Request)]
    public static class IUser_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(JoinGame_Invoke), typeof(JoinGame_Return) },
                { typeof(LeaveGame_Invoke), null },
                { typeof(RegisterPairing_Invoke), null },
                { typeof(UnregisterPairing_Invoke), null },
            };
        }

        [ProtoContract, TypeAlias]
        public class JoinGame_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public System.Int64 gameId;
            [ProtoMember(2)] public Domain.IGameObserver observer;

            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public Task<IValueGetable> InvokeAsync(object __target)
            {
                return null;
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class JoinGame_Return
            : IInterfacedPayload, IValueGetable, IPayloadActorRefUpdatable
        {
            [ProtoMember(1)] public System.Tuple<Domain.IGamePlayer, System.Int32, Domain.GameInfo> v;

            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public object Value
            {
                get { return v; }
            }

            void IPayloadActorRefUpdatable.Update(Action<object> updater)
            {
                if (v != null)
                {
                    if (v.Item1 != null) updater(v.Item1);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class LeaveGame_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public System.Int64 gameId;

            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public Task<IValueGetable> InvokeAsync(object __target)
            {
                return null;
            }
        }

        [ProtoContract, TypeAlias]
        public class RegisterPairing_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public Domain.IUserPairingObserver observer;

            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public Task<IValueGetable> InvokeAsync(object __target)
            {
                return null;
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class UnregisterPairing_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public Task<IValueGetable> InvokeAsync(object __target)
            {
                return null;
            }
        }
    }

    public interface IUser_NoReply
    {
        void JoinGame(System.Int64 gameId, Domain.IGameObserver observer);
        void LeaveGame(System.Int64 gameId);
        void RegisterPairing(Domain.IUserPairingObserver observer);
        void UnregisterPairing();
    }

    public class UserRef : InterfacedActorRef, IUser, IUser_NoReply
    {
        public override Type InterfaceType => typeof(IUser);

        public UserRef() : base(null)
        {
        }

        public UserRef(IRequestTarget target) : base(target)
        {
        }

        public UserRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IUser_NoReply WithNoReply()
        {
            return this;
        }

        public UserRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new UserRef(Target, requestWaiter, Timeout);
        }

        public UserRef WithTimeout(TimeSpan? timeout)
        {
            return new UserRef(Target, RequestWaiter, timeout);
        }

        public Task<System.Tuple<Domain.IGamePlayer, System.Int32, Domain.GameInfo>> JoinGame(System.Int64 gameId, Domain.IGameObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.JoinGame_Invoke { gameId = gameId, observer = (GameObserver)observer }
            };
            return SendRequestAndReceive<System.Tuple<Domain.IGamePlayer, System.Int32, Domain.GameInfo>>(requestMessage);
        }

        public Task LeaveGame(System.Int64 gameId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.LeaveGame_Invoke { gameId = gameId }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task RegisterPairing(Domain.IUserPairingObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.RegisterPairing_Invoke { observer = (UserPairingObserver)observer }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task UnregisterPairing()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.UnregisterPairing_Invoke {  }
            };
            return SendRequestAndWait(requestMessage);
        }

        void IUser_NoReply.JoinGame(System.Int64 gameId, Domain.IGameObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.JoinGame_Invoke { gameId = gameId, observer = (GameObserver)observer }
            };
            SendRequest(requestMessage);
        }

        void IUser_NoReply.LeaveGame(System.Int64 gameId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.LeaveGame_Invoke { gameId = gameId }
            };
            SendRequest(requestMessage);
        }

        void IUser_NoReply.RegisterPairing(Domain.IUserPairingObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.RegisterPairing_Invoke { observer = (UserPairingObserver)observer }
            };
            SendRequest(requestMessage);
        }

        void IUser_NoReply.UnregisterPairing()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.UnregisterPairing_Invoke {  }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIUser
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIUser Convert(IUser value)
        {
            if (value == null) return null;
            return new SurrogateForIUser { Target = ((UserRef)value).Target };
        }

        [ProtoConverter]
        public static IUser Convert(SurrogateForIUser value)
        {
            if (value == null) return null;
            return new UserRef(value.Target);
        }
    }
}

#endregion
#region Domain.IUserLogin

namespace Domain
{
    [PayloadTable(typeof(IUserLogin), PayloadTableKind.Request)]
    public static class IUserLogin_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(Login_Invoke), typeof(Login_Return) },
            };
        }

        [ProtoContract, TypeAlias]
        public class Login_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public System.String id;
            [ProtoMember(2)] public System.String password;
            [ProtoMember(3)] public Domain.IUserEventObserver observer;

            public Type GetInterfaceType()
            {
                return typeof(IUserLogin);
            }

            public Task<IValueGetable> InvokeAsync(object __target)
            {
                return null;
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class Login_Return
            : IInterfacedPayload, IValueGetable, IPayloadActorRefUpdatable
        {
            [ProtoMember(1)] public Domain.LoginResult v;

            public Type GetInterfaceType()
            {
                return typeof(IUserLogin);
            }

            public object Value
            {
                get { return v; }
            }

            void IPayloadActorRefUpdatable.Update(Action<object> updater)
            {
                if (v != null)
                {
                    if (v.User != null) updater(v.User);
                }
            }
        }
    }

    public interface IUserLogin_NoReply
    {
        void Login(System.String id, System.String password, Domain.IUserEventObserver observer);
    }

    public class UserLoginRef : InterfacedActorRef, IUserLogin, IUserLogin_NoReply
    {
        public override Type InterfaceType => typeof(IUserLogin);

        public UserLoginRef() : base(null)
        {
        }

        public UserLoginRef(IRequestTarget target) : base(target)
        {
        }

        public UserLoginRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IUserLogin_NoReply WithNoReply()
        {
            return this;
        }

        public UserLoginRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new UserLoginRef(Target, requestWaiter, Timeout);
        }

        public UserLoginRef WithTimeout(TimeSpan? timeout)
        {
            return new UserLoginRef(Target, RequestWaiter, timeout);
        }

        public Task<Domain.LoginResult> Login(System.String id, System.String password, Domain.IUserEventObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUserLogin_PayloadTable.Login_Invoke { id = id, password = password, observer = (UserEventObserver)observer }
            };
            return SendRequestAndReceive<Domain.LoginResult>(requestMessage);
        }

        void IUserLogin_NoReply.Login(System.String id, System.String password, Domain.IUserEventObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUserLogin_PayloadTable.Login_Invoke { id = id, password = password, observer = (UserEventObserver)observer }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIUserLogin
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIUserLogin Convert(IUserLogin value)
        {
            if (value == null) return null;
            return new SurrogateForIUserLogin { Target = ((UserLoginRef)value).Target };
        }

        [ProtoConverter]
        public static IUserLogin Convert(SurrogateForIUserLogin value)
        {
            if (value == null) return null;
            return new UserLoginRef(value.Target);
        }
    }
}

#endregion
#region SurrogateForINotificationChannel

namespace Domain
{
    [ProtoContract]
    public class SurrogateForINotificationChannel
    {
        [ProtoConverter]
        public static SurrogateForINotificationChannel Convert(INotificationChannel value)
        {
            if (value == null) return null;
            return new SurrogateForINotificationChannel();
        }

        [ProtoConverter]
        public static INotificationChannel Convert(SurrogateForINotificationChannel value)
        {
            return null;
        }
    }
}

#endregion
#region Domain.IGameObserver

namespace Domain
{
    [PayloadTable(typeof(IGameObserver), PayloadTableKind.Notification)]
    public static class IGameObserver_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[] {
                typeof(Abort_Invoke),
                typeof(Begin_Invoke),
                typeof(End_Invoke),
                typeof(Join_Invoke),
                typeof(Leave_Invoke),
                typeof(MakeMove_Invoke),
                typeof(Say_Invoke),
            };
        }

        [ProtoContract, TypeAlias]
        public class Abort_Invoke : IInterfacedPayload, IInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Abort();
            }
        }

        [ProtoContract, TypeAlias]
        public class Begin_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public System.Int32 currentPlayerId;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Begin(currentPlayerId);
            }
        }

        [ProtoContract, TypeAlias]
        public class End_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public System.Int32 winnerPlayerId;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).End(winnerPlayerId);
            }
        }

        [ProtoContract, TypeAlias]
        public class Join_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public System.Int32 playerId;
            [ProtoMember(2)] public System.Int64 userId;
            [ProtoMember(3)] public System.String userName;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Join(playerId, userId, userName);
            }
        }

        [ProtoContract, TypeAlias]
        public class Leave_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public System.Int32 playerId;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Leave(playerId);
            }
        }

        [ProtoContract, TypeAlias]
        public class MakeMove_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public System.Int32 playerId;
            [ProtoMember(2)] public Domain.PlacePosition pos;
            [ProtoMember(3)] public System.Int32 nextTurnPlayerId;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).MakeMove(playerId, pos, nextTurnPlayerId);
            }
        }

        [ProtoContract, TypeAlias]
        public class Say_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public System.Int32 playerId;
            [ProtoMember(2)] public System.String msg;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Say(playerId, msg);
            }
        }
    }

    public class GameObserver : InterfacedObserver, IGameObserver
    {
        public GameObserver()
            : base(null, 0)
        {
        }

        public GameObserver(INotificationChannel channel, int observerId = 0)
            : base(channel, observerId)
        {
        }

        public void Abort()
        {
            var payload = new IGameObserver_PayloadTable.Abort_Invoke {  };
            Notify(payload);
        }

        public void Begin(System.Int32 currentPlayerId)
        {
            var payload = new IGameObserver_PayloadTable.Begin_Invoke { currentPlayerId = currentPlayerId };
            Notify(payload);
        }

        public void End(System.Int32 winnerPlayerId)
        {
            var payload = new IGameObserver_PayloadTable.End_Invoke { winnerPlayerId = winnerPlayerId };
            Notify(payload);
        }

        public void Join(System.Int32 playerId, System.Int64 userId, System.String userName)
        {
            var payload = new IGameObserver_PayloadTable.Join_Invoke { playerId = playerId, userId = userId, userName = userName };
            Notify(payload);
        }

        public void Leave(System.Int32 playerId)
        {
            var payload = new IGameObserver_PayloadTable.Leave_Invoke { playerId = playerId };
            Notify(payload);
        }

        public void MakeMove(System.Int32 playerId, Domain.PlacePosition pos, System.Int32 nextTurnPlayerId)
        {
            var payload = new IGameObserver_PayloadTable.MakeMove_Invoke { playerId = playerId, pos = pos, nextTurnPlayerId = nextTurnPlayerId };
            Notify(payload);
        }

        public void Say(System.Int32 playerId, System.String msg)
        {
            var payload = new IGameObserver_PayloadTable.Say_Invoke { playerId = playerId, msg = msg };
            Notify(payload);
        }
    }

    [ProtoContract]
    public class SurrogateForIGameObserver
    {
        [ProtoMember(1)] public INotificationChannel Channel;
        [ProtoMember(2)] public int ObserverId;

        [ProtoConverter]
        public static SurrogateForIGameObserver Convert(IGameObserver value)
        {
            if (value == null) return null;
            var o = (GameObserver)value;
            return new SurrogateForIGameObserver { Channel = o.Channel, ObserverId = o.ObserverId };
        }

        [ProtoConverter]
        public static IGameObserver Convert(SurrogateForIGameObserver value)
        {
            if (value == null) return null;
            return new GameObserver(value.Channel, value.ObserverId);
        }
    }
}

#endregion
#region Domain.IUserEventObserver

namespace Domain
{
    [PayloadTable(typeof(IUserEventObserver), PayloadTableKind.Notification)]
    public static class IUserEventObserver_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[] {
                typeof(UserContextChange_Invoke),
            };
        }

        [ProtoContract, TypeAlias]
        public class UserContextChange_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public Domain.TrackableUserContextTracker userContextTracker;

            public Type GetInterfaceType()
            {
                return typeof(IUserEventObserver);
            }

            public void Invoke(object __target)
            {
                ((IUserEventObserver)__target).UserContextChange(userContextTracker);
            }
        }
    }

    public class UserEventObserver : InterfacedObserver, IUserEventObserver
    {
        public UserEventObserver()
            : base(null, 0)
        {
        }

        public UserEventObserver(INotificationChannel channel, int observerId = 0)
            : base(channel, observerId)
        {
        }

        public void UserContextChange(Domain.TrackableUserContextTracker userContextTracker)
        {
            var payload = new IUserEventObserver_PayloadTable.UserContextChange_Invoke { userContextTracker = userContextTracker };
            Notify(payload);
        }
    }

    [ProtoContract]
    public class SurrogateForIUserEventObserver
    {
        [ProtoMember(1)] public INotificationChannel Channel;
        [ProtoMember(2)] public int ObserverId;

        [ProtoConverter]
        public static SurrogateForIUserEventObserver Convert(IUserEventObserver value)
        {
            if (value == null) return null;
            var o = (UserEventObserver)value;
            return new SurrogateForIUserEventObserver { Channel = o.Channel, ObserverId = o.ObserverId };
        }

        [ProtoConverter]
        public static IUserEventObserver Convert(SurrogateForIUserEventObserver value)
        {
            if (value == null) return null;
            return new UserEventObserver(value.Channel, value.ObserverId);
        }
    }
}

#endregion
#region Domain.IUserPairingObserver

namespace Domain
{
    [PayloadTable(typeof(IUserPairingObserver), PayloadTableKind.Notification)]
    public static class IUserPairingObserver_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[] {
                typeof(MakePair_Invoke),
            };
        }

        [ProtoContract, TypeAlias]
        public class MakePair_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public System.Int64 gameId;
            [ProtoMember(2)] public System.String opponentName;

            public Type GetInterfaceType()
            {
                return typeof(IUserPairingObserver);
            }

            public void Invoke(object __target)
            {
                ((IUserPairingObserver)__target).MakePair(gameId, opponentName);
            }
        }
    }

    public class UserPairingObserver : InterfacedObserver, IUserPairingObserver
    {
        public UserPairingObserver()
            : base(null, 0)
        {
        }

        public UserPairingObserver(INotificationChannel channel, int observerId = 0)
            : base(channel, observerId)
        {
        }

        public void MakePair(System.Int64 gameId, System.String opponentName)
        {
            var payload = new IUserPairingObserver_PayloadTable.MakePair_Invoke { gameId = gameId, opponentName = opponentName };
            Notify(payload);
        }
    }

    [ProtoContract]
    public class SurrogateForIUserPairingObserver
    {
        [ProtoMember(1)] public INotificationChannel Channel;
        [ProtoMember(2)] public int ObserverId;

        [ProtoConverter]
        public static SurrogateForIUserPairingObserver Convert(IUserPairingObserver value)
        {
            if (value == null) return null;
            var o = (UserPairingObserver)value;
            return new SurrogateForIUserPairingObserver { Channel = o.Channel, ObserverId = o.ObserverId };
        }

        [ProtoConverter]
        public static IUserPairingObserver Convert(SurrogateForIUserPairingObserver value)
        {
            if (value == null) return null;
            return new UserPairingObserver(value.Channel, value.ObserverId);
        }
    }
}

#endregion
