// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Akka.Interfaced CodeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using Akka.Interfaced;
using Akka.Actor;
using ProtoBuf;
using TypeAlias;
using System.ComponentModel;

#region Domain.IGame

namespace Domain
{
    [PayloadTable(typeof(IGame), PayloadTableKind.Request)]
    public static class IGame_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(Join_Invoke), typeof(Join_Return) },
                { typeof(Leave_Invoke), null },
            };
        }

        [ProtoContract, TypeAlias]
        public class Join_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public long userId;
            [ProtoMember(2)] public string userName;
            [ProtoMember(3)] public Domain.IGameObserver observer;
            [ProtoMember(4)] public Domain.IGameUserObserver observerForUserActor;

            public Type GetInterfaceType()
            {
                return typeof(IGame);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IGame)__target).Join(userId, userName, observer, observerForUserActor);
                return (IValueGetable)(new Join_Return { v = __v });
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
                if (observerForUserActor != null)
                {
                    updater(observerForUserActor);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class Join_Return
            : IInterfacedPayload, IValueGetable
        {
            [ProtoMember(1)] public System.Tuple<int, Domain.GameInfo> v;

            public Type GetInterfaceType()
            {
                return typeof(IGame);
            }

            public object Value
            {
                get { return v; }
            }
        }

        [ProtoContract, TypeAlias]
        public class Leave_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public long userId;

            public Type GetInterfaceType()
            {
                return typeof(IGame);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IGame)__target).Leave(userId);
                return null;
            }
        }
    }

    public interface IGame_NoReply
    {
        void Join(long userId, string userName, Domain.IGameObserver observer, Domain.IGameUserObserver observerForUserActor);
        void Leave(long userId);
    }

    public class GameRef : InterfacedActorRef, IGame, IGame_NoReply
    {
        public override Type InterfaceType => typeof(IGame);

        public GameRef() : base(null)
        {
        }

        public GameRef(IRequestTarget target) : base(target)
        {
        }

        public GameRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IGame_NoReply WithNoReply()
        {
            return this;
        }

        public GameRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new GameRef(Target, requestWaiter, Timeout);
        }

        public GameRef WithTimeout(TimeSpan? timeout)
        {
            return new GameRef(Target, RequestWaiter, timeout);
        }

        public Task<System.Tuple<int, Domain.GameInfo>> Join(long userId, string userName, Domain.IGameObserver observer, Domain.IGameUserObserver observerForUserActor)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGame_PayloadTable.Join_Invoke { userId = userId, userName = userName, observer = (GameObserver)observer, observerForUserActor = (GameUserObserver)observerForUserActor }
            };
            return SendRequestAndReceive<System.Tuple<int, Domain.GameInfo>>(requestMessage);
        }

        public Task Leave(long userId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGame_PayloadTable.Leave_Invoke { userId = userId }
            };
            return SendRequestAndWait(requestMessage);
        }

        void IGame_NoReply.Join(long userId, string userName, Domain.IGameObserver observer, Domain.IGameUserObserver observerForUserActor)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGame_PayloadTable.Join_Invoke { userId = userId, userName = userName, observer = (GameObserver)observer, observerForUserActor = (GameUserObserver)observerForUserActor }
            };
            SendRequest(requestMessage);
        }

        void IGame_NoReply.Leave(long userId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGame_PayloadTable.Leave_Invoke { userId = userId }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIGame
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIGame Convert(IGame value)
        {
            if (value == null) return null;
            return new SurrogateForIGame { Target = ((GameRef)value).Target };
        }

        [ProtoConverter]
        public static IGame Convert(SurrogateForIGame value)
        {
            if (value == null) return null;
            return new GameRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(IGame))]
    public interface IGameSync : IInterfacedActorSync
    {
        System.Tuple<int, Domain.GameInfo> Join(long userId, string userName, Domain.IGameObserver observer, Domain.IGameUserObserver observerForUserActor);
        void Leave(long userId);
    }
}

#endregion
#region Domain.IGamePairMaker

namespace Domain
{
    [PayloadTable(typeof(IGamePairMaker), PayloadTableKind.Request)]
    public static class IGamePairMaker_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(RegisterPairing_Invoke), null },
                { typeof(UnregisterPairing_Invoke), null },
            };
        }

        [ProtoContract, TypeAlias]
        public class RegisterPairing_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public long userId;
            [ProtoMember(2)] public string userName;
            [ProtoMember(3)] public Domain.IUserPairingObserver observer;

            public Type GetInterfaceType()
            {
                return typeof(IGamePairMaker);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IGamePairMaker)__target).RegisterPairing(userId, userName, observer);
                return null;
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class UnregisterPairing_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public long userId;

            public Type GetInterfaceType()
            {
                return typeof(IGamePairMaker);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IGamePairMaker)__target).UnregisterPairing(userId);
                return null;
            }
        }
    }

    public interface IGamePairMaker_NoReply
    {
        void RegisterPairing(long userId, string userName, Domain.IUserPairingObserver observer);
        void UnregisterPairing(long userId);
    }

    public class GamePairMakerRef : InterfacedActorRef, IGamePairMaker, IGamePairMaker_NoReply
    {
        public override Type InterfaceType => typeof(IGamePairMaker);

        public GamePairMakerRef() : base(null)
        {
        }

        public GamePairMakerRef(IRequestTarget target) : base(target)
        {
        }

        public GamePairMakerRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IGamePairMaker_NoReply WithNoReply()
        {
            return this;
        }

        public GamePairMakerRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new GamePairMakerRef(Target, requestWaiter, Timeout);
        }

        public GamePairMakerRef WithTimeout(TimeSpan? timeout)
        {
            return new GamePairMakerRef(Target, RequestWaiter, timeout);
        }

        public Task RegisterPairing(long userId, string userName, Domain.IUserPairingObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePairMaker_PayloadTable.RegisterPairing_Invoke { userId = userId, userName = userName, observer = (UserPairingObserver)observer }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task UnregisterPairing(long userId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePairMaker_PayloadTable.UnregisterPairing_Invoke { userId = userId }
            };
            return SendRequestAndWait(requestMessage);
        }

        void IGamePairMaker_NoReply.RegisterPairing(long userId, string userName, Domain.IUserPairingObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePairMaker_PayloadTable.RegisterPairing_Invoke { userId = userId, userName = userName, observer = (UserPairingObserver)observer }
            };
            SendRequest(requestMessage);
        }

        void IGamePairMaker_NoReply.UnregisterPairing(long userId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePairMaker_PayloadTable.UnregisterPairing_Invoke { userId = userId }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIGamePairMaker
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIGamePairMaker Convert(IGamePairMaker value)
        {
            if (value == null) return null;
            return new SurrogateForIGamePairMaker { Target = ((GamePairMakerRef)value).Target };
        }

        [ProtoConverter]
        public static IGamePairMaker Convert(SurrogateForIGamePairMaker value)
        {
            if (value == null) return null;
            return new GamePairMakerRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(IGamePairMaker))]
    public interface IGamePairMakerSync : IInterfacedActorSync
    {
        void RegisterPairing(long userId, string userName, Domain.IUserPairingObserver observer);
        void UnregisterPairing(long userId);
    }
}

#endregion
#region Domain.IGamePlayer

namespace Domain
{
    [PayloadTable(typeof(IGamePlayer), PayloadTableKind.Request)]
    public static class IGamePlayer_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(MakeMove_Invoke), null },
                { typeof(Say_Invoke), null },
            };
        }

        [ProtoContract, TypeAlias]
        public class MakeMove_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadTagOverridable
        {
            [ProtoMember(1)] public Domain.PlacePosition pos;
            [ProtoMember(2)] public long playerUserId;

            public Type GetInterfaceType()
            {
                return typeof(IGamePlayer);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IGamePlayer)__target).MakeMove(pos, playerUserId);
                return null;
            }

            void IPayloadTagOverridable.SetTag(object value)
            {
                playerUserId = (long)value;
            }
        }

        [ProtoContract, TypeAlias]
        public class Say_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadTagOverridable
        {
            [ProtoMember(1)] public string msg;
            [ProtoMember(2)] public long playerUserId;

            public Type GetInterfaceType()
            {
                return typeof(IGamePlayer);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IGamePlayer)__target).Say(msg, playerUserId);
                return null;
            }

            void IPayloadTagOverridable.SetTag(object value)
            {
                playerUserId = (long)value;
            }
        }
    }

    public interface IGamePlayer_NoReply
    {
        void MakeMove(Domain.PlacePosition pos, long playerUserId = 0);
        void Say(string msg, long playerUserId = 0);
    }

    public class GamePlayerRef : InterfacedActorRef, IGamePlayer, IGamePlayer_NoReply
    {
        public override Type InterfaceType => typeof(IGamePlayer);

        public GamePlayerRef() : base(null)
        {
        }

        public GamePlayerRef(IRequestTarget target) : base(target)
        {
        }

        public GamePlayerRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IGamePlayer_NoReply WithNoReply()
        {
            return this;
        }

        public GamePlayerRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new GamePlayerRef(Target, requestWaiter, Timeout);
        }

        public GamePlayerRef WithTimeout(TimeSpan? timeout)
        {
            return new GamePlayerRef(Target, RequestWaiter, timeout);
        }

        public Task MakeMove(Domain.PlacePosition pos, long playerUserId = 0)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePlayer_PayloadTable.MakeMove_Invoke { pos = pos, playerUserId = playerUserId }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task Say(string msg, long playerUserId = 0)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePlayer_PayloadTable.Say_Invoke { msg = msg, playerUserId = playerUserId }
            };
            return SendRequestAndWait(requestMessage);
        }

        void IGamePlayer_NoReply.MakeMove(Domain.PlacePosition pos, long playerUserId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePlayer_PayloadTable.MakeMove_Invoke { pos = pos, playerUserId = playerUserId }
            };
            SendRequest(requestMessage);
        }

        void IGamePlayer_NoReply.Say(string msg, long playerUserId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IGamePlayer_PayloadTable.Say_Invoke { msg = msg, playerUserId = playerUserId }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIGamePlayer
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIGamePlayer Convert(IGamePlayer value)
        {
            if (value == null) return null;
            return new SurrogateForIGamePlayer { Target = ((GamePlayerRef)value).Target };
        }

        [ProtoConverter]
        public static IGamePlayer Convert(SurrogateForIGamePlayer value)
        {
            if (value == null) return null;
            return new GamePlayerRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(IGamePlayer))]
    public interface IGamePlayerSync : IInterfacedActorSync
    {
        void MakeMove(Domain.PlacePosition pos, long playerUserId = 0);
        void Say(string msg, long playerUserId = 0);
    }
}

#endregion
#region Domain.IUser

namespace Domain
{
    [PayloadTable(typeof(IUser), PayloadTableKind.Request)]
    public static class IUser_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(JoinGame_Invoke), typeof(JoinGame_Return) },
                { typeof(LeaveGame_Invoke), null },
                { typeof(RegisterPairing_Invoke), null },
                { typeof(UnregisterPairing_Invoke), null },
            };
        }

        [ProtoContract, TypeAlias]
        public class JoinGame_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public long gameId;
            [ProtoMember(2)] public Domain.IGameObserver observer;

            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IUser)__target).JoinGame(gameId, observer);
                return (IValueGetable)(new JoinGame_Return { v = __v });
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class JoinGame_Return
            : IInterfacedPayload, IValueGetable, IPayloadActorRefUpdatable
        {
            [ProtoMember(1)] public System.Tuple<Domain.IGamePlayer, int, Domain.GameInfo> v;

            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public object Value
            {
                get { return v; }
            }

            void IPayloadActorRefUpdatable.Update(Action<object> updater)
            {
                if (v != null)
                {
                    if (v.Item1 != null) updater(v.Item1);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class LeaveGame_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            [ProtoMember(1)] public long gameId;

            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IUser)__target).LeaveGame(gameId);
                return null;
            }
        }

        [ProtoContract, TypeAlias]
        public class RegisterPairing_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public Domain.IUserPairingObserver observer;

            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IUser)__target).RegisterPairing(observer);
                return null;
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class UnregisterPairing_Invoke
            : IInterfacedPayload, IAsyncInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IUser);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                await ((IUser)__target).UnregisterPairing();
                return null;
            }
        }
    }

    public interface IUser_NoReply
    {
        void JoinGame(long gameId, Domain.IGameObserver observer);
        void LeaveGame(long gameId);
        void RegisterPairing(Domain.IUserPairingObserver observer);
        void UnregisterPairing();
    }

    public class UserRef : InterfacedActorRef, IUser, IUser_NoReply
    {
        public override Type InterfaceType => typeof(IUser);

        public UserRef() : base(null)
        {
        }

        public UserRef(IRequestTarget target) : base(target)
        {
        }

        public UserRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IUser_NoReply WithNoReply()
        {
            return this;
        }

        public UserRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new UserRef(Target, requestWaiter, Timeout);
        }

        public UserRef WithTimeout(TimeSpan? timeout)
        {
            return new UserRef(Target, RequestWaiter, timeout);
        }

        public Task<System.Tuple<Domain.IGamePlayer, int, Domain.GameInfo>> JoinGame(long gameId, Domain.IGameObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.JoinGame_Invoke { gameId = gameId, observer = (GameObserver)observer }
            };
            return SendRequestAndReceive<System.Tuple<Domain.IGamePlayer, int, Domain.GameInfo>>(requestMessage);
        }

        public Task LeaveGame(long gameId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.LeaveGame_Invoke { gameId = gameId }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task RegisterPairing(Domain.IUserPairingObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.RegisterPairing_Invoke { observer = (UserPairingObserver)observer }
            };
            return SendRequestAndWait(requestMessage);
        }

        public Task UnregisterPairing()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.UnregisterPairing_Invoke {  }
            };
            return SendRequestAndWait(requestMessage);
        }

        void IUser_NoReply.JoinGame(long gameId, Domain.IGameObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.JoinGame_Invoke { gameId = gameId, observer = (GameObserver)observer }
            };
            SendRequest(requestMessage);
        }

        void IUser_NoReply.LeaveGame(long gameId)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.LeaveGame_Invoke { gameId = gameId }
            };
            SendRequest(requestMessage);
        }

        void IUser_NoReply.RegisterPairing(Domain.IUserPairingObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.RegisterPairing_Invoke { observer = (UserPairingObserver)observer }
            };
            SendRequest(requestMessage);
        }

        void IUser_NoReply.UnregisterPairing()
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUser_PayloadTable.UnregisterPairing_Invoke {  }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIUser
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIUser Convert(IUser value)
        {
            if (value == null) return null;
            return new SurrogateForIUser { Target = ((UserRef)value).Target };
        }

        [ProtoConverter]
        public static IUser Convert(SurrogateForIUser value)
        {
            if (value == null) return null;
            return new UserRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(IUser))]
    public interface IUserSync : IInterfacedActorSync
    {
        System.Tuple<Domain.IGamePlayer, int, Domain.GameInfo> JoinGame(long gameId, Domain.IGameObserver observer);
        void LeaveGame(long gameId);
        void RegisterPairing(Domain.IUserPairingObserver observer);
        void UnregisterPairing();
    }
}

#endregion
#region Domain.IUserLogin

namespace Domain
{
    [PayloadTable(typeof(IUserLogin), PayloadTableKind.Request)]
    public static class IUserLogin_PayloadTable
    {
        public static Type[,] GetPayloadTypes()
        {
            return new Type[,] {
                { typeof(Login_Invoke), typeof(Login_Return) },
            };
        }

        [ProtoContract, TypeAlias]
        public class Login_Invoke
            : IInterfacedPayload, IAsyncInvokable, IPayloadObserverUpdatable
        {
            [ProtoMember(1)] public string id;
            [ProtoMember(2)] public string password;
            [ProtoMember(3)] public Domain.IUserEventObserver observer;

            public Type GetInterfaceType()
            {
                return typeof(IUserLogin);
            }

            public async Task<IValueGetable> InvokeAsync(object __target)
            {
                var __v = await ((IUserLogin)__target).Login(id, password, observer);
                return (IValueGetable)(new Login_Return { v = __v });
            }

            void IPayloadObserverUpdatable.Update(Action<IInterfacedObserver> updater)
            {
                if (observer != null)
                {
                    updater(observer);
                }
            }
        }

        [ProtoContract, TypeAlias]
        public class Login_Return
            : IInterfacedPayload, IValueGetable, IPayloadActorRefUpdatable
        {
            [ProtoMember(1)] public Domain.LoginResult v;

            public Type GetInterfaceType()
            {
                return typeof(IUserLogin);
            }

            public object Value
            {
                get { return v; }
            }

            void IPayloadActorRefUpdatable.Update(Action<object> updater)
            {
                if (v != null)
                {
                    if (v.User != null) updater(v.User);
                }
            }
        }
    }

    public interface IUserLogin_NoReply
    {
        void Login(string id, string password, Domain.IUserEventObserver observer);
    }

    public class UserLoginRef : InterfacedActorRef, IUserLogin, IUserLogin_NoReply
    {
        public override Type InterfaceType => typeof(IUserLogin);

        public UserLoginRef() : base(null)
        {
        }

        public UserLoginRef(IRequestTarget target) : base(target)
        {
        }

        public UserLoginRef(IRequestTarget target, IRequestWaiter requestWaiter, TimeSpan? timeout = null) : base(target, requestWaiter, timeout)
        {
        }

        public IUserLogin_NoReply WithNoReply()
        {
            return this;
        }

        public UserLoginRef WithRequestWaiter(IRequestWaiter requestWaiter)
        {
            return new UserLoginRef(Target, requestWaiter, Timeout);
        }

        public UserLoginRef WithTimeout(TimeSpan? timeout)
        {
            return new UserLoginRef(Target, RequestWaiter, timeout);
        }

        public Task<Domain.LoginResult> Login(string id, string password, Domain.IUserEventObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUserLogin_PayloadTable.Login_Invoke { id = id, password = password, observer = (UserEventObserver)observer }
            };
            return SendRequestAndReceive<Domain.LoginResult>(requestMessage);
        }

        void IUserLogin_NoReply.Login(string id, string password, Domain.IUserEventObserver observer)
        {
            var requestMessage = new RequestMessage {
                InvokePayload = new IUserLogin_PayloadTable.Login_Invoke { id = id, password = password, observer = (UserEventObserver)observer }
            };
            SendRequest(requestMessage);
        }
    }

    [ProtoContract]
    public class SurrogateForIUserLogin
    {
        [ProtoMember(1)] public IRequestTarget Target;

        [ProtoConverter]
        public static SurrogateForIUserLogin Convert(IUserLogin value)
        {
            if (value == null) return null;
            return new SurrogateForIUserLogin { Target = ((UserLoginRef)value).Target };
        }

        [ProtoConverter]
        public static IUserLogin Convert(SurrogateForIUserLogin value)
        {
            if (value == null) return null;
            return new UserLoginRef(value.Target);
        }
    }

    [AlternativeInterface(typeof(IUserLogin))]
    public interface IUserLoginSync : IInterfacedActorSync
    {
        Domain.LoginResult Login(string id, string password, Domain.IUserEventObserver observer);
    }
}

#endregion
#region Domain.IGameObserver

namespace Domain
{
    [PayloadTable(typeof(IGameObserver), PayloadTableKind.Notification)]
    public static class IGameObserver_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[] {
                typeof(Abort_Invoke),
                typeof(Begin_Invoke),
                typeof(End_Invoke),
                typeof(Join_Invoke),
                typeof(Leave_Invoke),
                typeof(MakeMove_Invoke),
                typeof(Say_Invoke),
            };
        }

        [ProtoContract, TypeAlias]
        public class Abort_Invoke : IInterfacedPayload, IInvokable
        {
            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Abort();
            }
        }

        [ProtoContract, TypeAlias]
        public class Begin_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public int currentPlayerId;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Begin(currentPlayerId);
            }
        }

        [ProtoContract, TypeAlias]
        public class End_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public int winnerPlayerId;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).End(winnerPlayerId);
            }
        }

        [ProtoContract, TypeAlias]
        public class Join_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public int playerId;
            [ProtoMember(2)] public long userId;
            [ProtoMember(3)] public string userName;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Join(playerId, userId, userName);
            }
        }

        [ProtoContract, TypeAlias]
        public class Leave_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public int playerId;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Leave(playerId);
            }
        }

        [ProtoContract, TypeAlias]
        public class MakeMove_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public int playerId;
            [ProtoMember(2)] public Domain.PlacePosition pos;
            [ProtoMember(3)] public int nextTurnPlayerId;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).MakeMove(playerId, pos, nextTurnPlayerId);
            }
        }

        [ProtoContract, TypeAlias]
        public class Say_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public int playerId;
            [ProtoMember(2)] public string msg;

            public Type GetInterfaceType()
            {
                return typeof(IGameObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameObserver)__target).Say(playerId, msg);
            }
        }
    }

    public class GameObserver : InterfacedObserver, IGameObserver
    {
        public GameObserver()
            : base(null, 0)
        {
        }

        public GameObserver(INotificationChannel channel, int observerId = 0)
            : base(channel, observerId)
        {
        }

        public void Abort()
        {
            var payload = new IGameObserver_PayloadTable.Abort_Invoke {  };
            Notify(payload);
        }

        public void Begin(int currentPlayerId)
        {
            var payload = new IGameObserver_PayloadTable.Begin_Invoke { currentPlayerId = currentPlayerId };
            Notify(payload);
        }

        public void End(int winnerPlayerId)
        {
            var payload = new IGameObserver_PayloadTable.End_Invoke { winnerPlayerId = winnerPlayerId };
            Notify(payload);
        }

        public void Join(int playerId, long userId, string userName)
        {
            var payload = new IGameObserver_PayloadTable.Join_Invoke { playerId = playerId, userId = userId, userName = userName };
            Notify(payload);
        }

        public void Leave(int playerId)
        {
            var payload = new IGameObserver_PayloadTable.Leave_Invoke { playerId = playerId };
            Notify(payload);
        }

        public void MakeMove(int playerId, Domain.PlacePosition pos, int nextTurnPlayerId)
        {
            var payload = new IGameObserver_PayloadTable.MakeMove_Invoke { playerId = playerId, pos = pos, nextTurnPlayerId = nextTurnPlayerId };
            Notify(payload);
        }

        public void Say(int playerId, string msg)
        {
            var payload = new IGameObserver_PayloadTable.Say_Invoke { playerId = playerId, msg = msg };
            Notify(payload);
        }
    }

    [ProtoContract]
    public class SurrogateForIGameObserver
    {
        [ProtoMember(1)] public INotificationChannel Channel;
        [ProtoMember(2)] public int ObserverId;

        [ProtoConverter]
        public static SurrogateForIGameObserver Convert(IGameObserver value)
        {
            if (value == null) return null;
            var o = (GameObserver)value;
            return new SurrogateForIGameObserver { Channel = o.Channel, ObserverId = o.ObserverId };
        }

        [ProtoConverter]
        public static IGameObserver Convert(SurrogateForIGameObserver value)
        {
            if (value == null) return null;
            return new GameObserver(value.Channel, value.ObserverId);
        }
    }

    [AlternativeInterface(typeof(IGameObserver))]
    public interface IGameObserverAsync : IInterfacedObserverSync
    {
        Task Abort();
        Task Begin(int currentPlayerId);
        Task End(int winnerPlayerId);
        Task Join(int playerId, long userId, string userName);
        Task Leave(int playerId);
        Task MakeMove(int playerId, Domain.PlacePosition pos, int nextTurnPlayerId);
        Task Say(int playerId, string msg);
    }
}

#endregion
#region Domain.IGameUserObserver

namespace Domain
{
    [PayloadTable(typeof(IGameUserObserver), PayloadTableKind.Notification)]
    public static class IGameUserObserver_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[] {
                typeof(Begin_Invoke),
                typeof(End_Invoke),
            };
        }

        [ProtoContract, TypeAlias]
        public class Begin_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public long gameId;

            public Type GetInterfaceType()
            {
                return typeof(IGameUserObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameUserObserver)__target).Begin(gameId);
            }
        }

        [ProtoContract, TypeAlias]
        public class End_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public long gameId;
            [ProtoMember(2)] public Domain.GameResult result;

            public Type GetInterfaceType()
            {
                return typeof(IGameUserObserver);
            }

            public void Invoke(object __target)
            {
                ((IGameUserObserver)__target).End(gameId, result);
            }
        }
    }

    public class GameUserObserver : InterfacedObserver, IGameUserObserver
    {
        public GameUserObserver()
            : base(null, 0)
        {
        }

        public GameUserObserver(INotificationChannel channel, int observerId = 0)
            : base(channel, observerId)
        {
        }

        public void Begin(long gameId)
        {
            var payload = new IGameUserObserver_PayloadTable.Begin_Invoke { gameId = gameId };
            Notify(payload);
        }

        public void End(long gameId, Domain.GameResult result)
        {
            var payload = new IGameUserObserver_PayloadTable.End_Invoke { gameId = gameId, result = result };
            Notify(payload);
        }
    }

    [ProtoContract]
    public class SurrogateForIGameUserObserver
    {
        [ProtoMember(1)] public INotificationChannel Channel;
        [ProtoMember(2)] public int ObserverId;

        [ProtoConverter]
        public static SurrogateForIGameUserObserver Convert(IGameUserObserver value)
        {
            if (value == null) return null;
            var o = (GameUserObserver)value;
            return new SurrogateForIGameUserObserver { Channel = o.Channel, ObserverId = o.ObserverId };
        }

        [ProtoConverter]
        public static IGameUserObserver Convert(SurrogateForIGameUserObserver value)
        {
            if (value == null) return null;
            return new GameUserObserver(value.Channel, value.ObserverId);
        }
    }

    [AlternativeInterface(typeof(IGameUserObserver))]
    public interface IGameUserObserverAsync : IInterfacedObserverSync
    {
        Task Begin(long gameId);
        Task End(long gameId, Domain.GameResult result);
    }
}

#endregion
#region Domain.IUserEventObserver

namespace Domain
{
    [PayloadTable(typeof(IUserEventObserver), PayloadTableKind.Notification)]
    public static class IUserEventObserver_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[] {
                typeof(UserContextChange_Invoke),
            };
        }

        [ProtoContract, TypeAlias]
        public class UserContextChange_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public Domain.TrackableUserContextTracker userContextTracker;

            public Type GetInterfaceType()
            {
                return typeof(IUserEventObserver);
            }

            public void Invoke(object __target)
            {
                ((IUserEventObserver)__target).UserContextChange(userContextTracker);
            }
        }
    }

    public class UserEventObserver : InterfacedObserver, IUserEventObserver
    {
        public UserEventObserver()
            : base(null, 0)
        {
        }

        public UserEventObserver(INotificationChannel channel, int observerId = 0)
            : base(channel, observerId)
        {
        }

        public void UserContextChange(Domain.TrackableUserContextTracker userContextTracker)
        {
            var payload = new IUserEventObserver_PayloadTable.UserContextChange_Invoke { userContextTracker = userContextTracker };
            Notify(payload);
        }
    }

    [ProtoContract]
    public class SurrogateForIUserEventObserver
    {
        [ProtoMember(1)] public INotificationChannel Channel;
        [ProtoMember(2)] public int ObserverId;

        [ProtoConverter]
        public static SurrogateForIUserEventObserver Convert(IUserEventObserver value)
        {
            if (value == null) return null;
            var o = (UserEventObserver)value;
            return new SurrogateForIUserEventObserver { Channel = o.Channel, ObserverId = o.ObserverId };
        }

        [ProtoConverter]
        public static IUserEventObserver Convert(SurrogateForIUserEventObserver value)
        {
            if (value == null) return null;
            return new UserEventObserver(value.Channel, value.ObserverId);
        }
    }

    [AlternativeInterface(typeof(IUserEventObserver))]
    public interface IUserEventObserverAsync : IInterfacedObserverSync
    {
        Task UserContextChange(Domain.TrackableUserContextTracker userContextTracker);
    }
}

#endregion
#region Domain.IUserPairingObserver

namespace Domain
{
    [PayloadTable(typeof(IUserPairingObserver), PayloadTableKind.Notification)]
    public static class IUserPairingObserver_PayloadTable
    {
        public static Type[] GetPayloadTypes()
        {
            return new Type[] {
                typeof(MakePair_Invoke),
            };
        }

        [ProtoContract, TypeAlias]
        public class MakePair_Invoke : IInterfacedPayload, IInvokable
        {
            [ProtoMember(1)] public long gameId;
            [ProtoMember(2)] public string opponentName;

            public Type GetInterfaceType()
            {
                return typeof(IUserPairingObserver);
            }

            public void Invoke(object __target)
            {
                ((IUserPairingObserver)__target).MakePair(gameId, opponentName);
            }
        }
    }

    public class UserPairingObserver : InterfacedObserver, IUserPairingObserver
    {
        public UserPairingObserver()
            : base(null, 0)
        {
        }

        public UserPairingObserver(INotificationChannel channel, int observerId = 0)
            : base(channel, observerId)
        {
        }

        public void MakePair(long gameId, string opponentName)
        {
            var payload = new IUserPairingObserver_PayloadTable.MakePair_Invoke { gameId = gameId, opponentName = opponentName };
            Notify(payload);
        }
    }

    [ProtoContract]
    public class SurrogateForIUserPairingObserver
    {
        [ProtoMember(1)] public INotificationChannel Channel;
        [ProtoMember(2)] public int ObserverId;

        [ProtoConverter]
        public static SurrogateForIUserPairingObserver Convert(IUserPairingObserver value)
        {
            if (value == null) return null;
            var o = (UserPairingObserver)value;
            return new SurrogateForIUserPairingObserver { Channel = o.Channel, ObserverId = o.ObserverId };
        }

        [ProtoConverter]
        public static IUserPairingObserver Convert(SurrogateForIUserPairingObserver value)
        {
            if (value == null) return null;
            return new UserPairingObserver(value.Channel, value.ObserverId);
        }
    }

    [AlternativeInterface(typeof(IUserPairingObserver))]
    public interface IUserPairingObserverAsync : IInterfacedObserverSync
    {
        Task MakePair(long gameId, string opponentName);
    }
}

#endregion
